(globals
    version = 3
    io_order = default
)

(iopad
  (bottomright
    (inst name="corner_cell_1")
  )
  (topleft
    (inst name="corner_cell_3")
  )
  (bottomleft
    (inst name="corner_cell_0")
  )
  (topright
    (inst name="corner_cell_2")
  )

###### left side (W, bottom to top)
###  (left
###    (inst name="iocell_AVDD[0]"   offset= 250 ) 
###    (inst name="iocell_AVSS[0]"   offset= 325 )
###    (inst name="iocell_VDD[2]"    offset= 400 )
###    (inst name="iocell_VSS[2]"    offset= 475 ) 
###    (inst name="iocell_VDD[1]"    offset= 550 ) 
###    (inst name="iocell_VSS[1]"    offset= 625 ) 
###    (inst name="iocell_VDD[0]"    offset= 700 ) 
###    (inst name="iocell_VSS[0]"    offset= 775 )
###    (inst name="iocell_AVDD[2]"       offset=850)
###    (inst name="iocell_AVSS[2]"        offset=925)
###    (inst name="iocell_DVDD[0]"       offset=1000)
###    (inst name="iocell_START"         offset=1075)
###  )
###### bottom side (S, left to right)
###  (bottom
###    (inst name="iocell_ref2"  offset= 250 ) 
###    (inst name="iocell_ext0"  offset= 325 ) 
###    (inst name="iocell_extA"  offset= 400 ) 
###    (inst name="iocell_extB"   offset= 475 ) 
###    (inst name="iocell_AVDD[1]"  offset= 550 ) 
###    (inst name="iocell_AVSS[1]"  offset= 625 ) 
###    (inst name="iocell_clock_io"          offset=700 ) 
###    (inst name="iocell_DVSS[0]"       offset=775 ) 
###    (inst name="iocell_VDD[3]"        offset=850 ) 
###    (inst name="iocell_VSS[3]"        offset=925 ) 
###    (inst name="iocell_CS2"           offset=1000) 
###    (inst name="iocell_clock2_io"     offset=1075)
###  )
###### right side (E, bottom to top)
###  (right
###    (inst name="iocell_reset_io"       offset=250) 
###    (inst name="iocell_CS1"            offset=325)
###    (inst name="iocell_SDI1"           offset=400) 
###    (inst name="iocell_BUSY"           offset=475) 
###    (inst name="iocell_DVDD[1]"       offset=550) 
###    (inst name="iocell_SDO1"           offset=625) 
###    (inst name="iocell_DVDD_control"   offset=700) 
###    (inst name="iocell_DVSS[1]"        offset=775) 
###    (inst name="iocell_ref0"           offset=850)
###    (inst name="iocell_ref1"           offset=925)
###    (inst name="iocell_VSS[4]"        offset=1000)
###    (inst name="iocell_VDD[4]"        offset=1075)
###  )
###### top side (N, left to right)
###  (top
###    (inst name="iocell_BP_MUX_OUT[7]"  offset=250) 
###    (inst name="iocell_BP_MUX_OUT[6]"  offset=325)
###    (inst name="iocell_BP_MUX_OUT[5]"  offset=400) 
###    (inst name="iocell_BP_MUX_OUT[4]"  offset=475) 
###    (inst name="iocell_BP_MUX_OUT[3]"  offset=550) 
###    (inst name="iocell_BP_MUX_OUT[2]"  offset=625) 
###    (inst name="iocell_BP_MUX_OUT[1]"  offset=700) 
###    (inst name="iocell_BP_MUX_OUT[0]"  offset=775) 
###    (inst name="iocell_BP_MUX_SAMPLED" offset=850)
###    (inst name="iocell_BP_MUX_READY"   offset=925)
###    (inst name="iocell_VSS[5]"        offset=1000)
###    (inst name="iocell_VDD[5]"        offset=1075)
###  )
)
